ALTER TABLE FISIKS.PACIENTEANTECEDENTES
 ADD (APAOBSERVACION  VARCHAR2(45));

ALTER TABLE FISIKS.PROFESIONAL
 ADD (PROACTIVO  VARCHAR2(1));

ALTER TABLE FISIKS.SESIONDETALLE DROP COLUMN DSE_TRAID;

ALTER TABLE FISIKS.SESION
 ADD (SES_TSTID  INTEGER);

ALTER TABLE FISIKS.SESION
 ADD CONSTRAINT FK_SES_TEST
 FOREIGN KEY (SES_TSTID) 
 REFERENCES FISIKS.TEST (TSTID);

CREATE TABLE MATRICULA (
  mtrId INT NOT NULL,
  mtrDescripcion VARCHAR2(45) NULL,
  PRIMARY KEY (mtrId));


CREATE SEQUENCE mtrid
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER trg_mtrid BEFORE INSERT ON matricula  FOR EACH ROW
BEGIN   SELECT mtrid.NEXTVAL INTO :new.mtrid FROM DUAL; END;
/


CREATE TABLE ProfesionalMatricula(
  pmtId INT NOT NULL,
  pmt_proId INT NULL,
  pmt_mtrId INT NULL,
  PRIMARY KEY (pmtId),
  CONSTRAINT fk_pmt_profesional
    FOREIGN KEY (pmt_proId)
    REFERENCES Profesional(proId),
    CONSTRAINT fk_pmt_matricula
    FOREIGN KEY (pmt_mtrId)
    REFERENCES matricula(mtrId));

ALTER TABLE FISIKS.SESION
 ADD (SES_PROID  INTEGER);

ALTER TABLE FISIKS.SESION ADD (
  CONSTRAINT FK_SES_PROFESIONAL
 FOREIGN KEY (SES_PROID) 
 REFERENCES FISIKS.PROFESIONAL (PROID));


ALTER TABLE FISIKS.PROFESIONAL DROP COLUMN PROMATRICULA;

ALTER TABLE FISIKS.PERSONA
MODIFY(PSNNRODCTO VARCHAR2(9));

ALTER TABLE FISIKS.TIPODIA
 DROP PRIMARY KEY CASCADE;

DROP TABLE FISIKS.TIPODIA CASCADE CONSTRAINTS;

CREATE TABLE FISIKS.DIATIPO
(
  TDAID           INTEGER                       NOT NULL,
  TDADESCRIPCION  VARCHAR2(45 BYTE)
)
TABLESPACE FISIKS_TBL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER FISIKS.trg_tdaid BEFORE INSERT ON FISIKS.DIATIPO  FOR EACH ROW
BEGIN   SELECT tdaid.NEXTVAL INTO :new.tdaid FROM DUAL; END;
/


ALTER TABLE FISIKS.DIATIPO ADD (
  PRIMARY KEY
 (TDAID)
    USING INDEX 
    TABLESPACE FISIKS_TBL
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE PACIENTE
ADD PAEPESO DECIMAL(8,2);

ALTER TABLE FISIKS.DOMICILIO
 ADD (DOMDESCRIPCION  VARCHAR2(45));


ALTER TABLE FISIKS.OBRASOCIAL
 ADD (OSOSIGLA  VARCHAR2(45));


