
CREATE TABLE PARAMETROS(
  prmId INT NULL,
  prmDescripcion varchar2(45) NULL,
  prmValorNum1 varchar2 (45) null,
  prmValorNum2 varchar2 (45) null,
  prmValorChar1 varchar2 (45) null,
  prmValorChar2 varchar2 (45) null,
  prmValorFech1 varchar2 (45) null,
  prmValorFech2 varchar2 (45) null,
  PRIMARY KEY (prmId)
  );


CREATE SEQUENCE prmId
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER trg_prmid BEFORE INSERT ON parametros FOR EACH ROW
BEGIN   SELECT prmid.NEXTVAL INTO :new.prmid FROM DUAL; END;
/



INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'LUNES');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'MARTES');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'MIERCOLES');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'JUEVES');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'VIERNES');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'SABADO');

INSERT INTO FISIKS.DIA (DIAID, DIADESCRIPCION) 
VALUES (0,'DOMINGO');

INSERT INTO FISIKS.PAIS (PASID, PASDESCRIPCION) 
VALUES ( 0,'ARGENTINA');


INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'BUENOS AIRES',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'CATAMARCA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'CHACO',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'CHUBUT',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'CORRIENTES',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'CORDOBA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'ENTRE RIOS',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'FORMOSA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'JUJUY',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'LA PAMPA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'LA RIOJA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'MENDOZA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'MISIONES',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'NEUQUEN',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'RIO NEGRO',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SALTA',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SAN JUAN',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SAN LUIS',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SANTA CRUZ',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SANTA FE',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'SANTIAGO DEL ESTERO',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'TIERRA DEL FUEGO',1);
INSERT INTO FISIKS.PROVINCIA (PVCID, PVCDESCRIPCION, PVC_PASID) VALUES ( 0, 'TUCUMAN',1);


INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'ALMAFUERTE', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'ALTA GRACIA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'ARROYITO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'BELL VILLE', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'COLONIA CAROYA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'CORDOBA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'CORONEL MOLDES', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'CORRAL DE BUSTOS', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'COSQUIN', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'CRUZ DEL EJE', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'DEAN FUNES', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'GENERAL CABRERA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'HERNANDO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'HUINCA RENANCO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'JESUS MARIA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LABOULAYE', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LA CALERA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LA CARLOTA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LA FALDA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LAS VARILLAS', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'LEONES', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'MARCOS JUAREZ', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'MORTEROS', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'OLIVA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'ONCATIVO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'RIO CEBALLOS', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'RIO CUARTO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'RIO SEGUNDO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'RIO TERCERO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'SAN FRANCISCO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'UNQUILLO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA ALLENDE', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA CARLOS PAZ', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA DEL ROSARIO', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA DOLORES', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA MARIA', 6);
INSERT INTO FISIKS.LOCALIDAD (LOCID, LOCDESCRIPCION, LOC_PVCID) VALUES ( 0,'VILLA NUEVA', 6);



INSERT INTO FISIKS.TIPODOCUMENTO (TPDID, TPDDESCRIPCION) VALUES (0,'DNI');
INSERT INTO FISIKS.TIPODOCUMENTO (TPDID, TPDDESCRIPCION) VALUES (0,'CI');
INSERT INTO FISIKS.TIPODOCUMENTO (TPDID, TPDDESCRIPCION) VALUES (0,'LC');
INSERT INTO FISIKS.TIPODOCUMENTO (TPDID, TPDDESCRIPCION) VALUES (0,'LE');

INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'ELECTROANALGESIA');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'MAGNETO TERAPIA');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'ULTRASONIDO');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'MASAJES');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'APLICACION FRIO');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'RADIOFRECUENCIA');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'ONDAS CORTAS');
INSERT INTO FISIKS.TRATAMIENTO ( TRAID, TRADESCRIPCION) VALUES (0,'EJERCICIOS');




INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'COLUMNA',1 , NULL);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'MIEMBRO SUPERIOR',1 , NULL);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'MIEMBRO INFERIOR', 1, NULL);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'CERVICAL', 2, 1);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'LUMBAR', 1, 1);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'DORSAL', 1, 1);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'SACRO', 1, 1);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'HOMBRO', 2,2);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'CODO', 2, 2);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'MANO', 2, 2);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'MUÑECA', 2,2);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'CADERA', 3,3);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'TOBILLO',3,3);
INSERT INTO FISIKS.ZONACUERPO (ZCUID, ZCUDESCRIPCION, ZCUNIVEL, ZCUIDPADRE) VALUES ( 0,'PIE', 3, 3);


INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'DISPONIBLE',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'ASIGNADO',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'EN ESPERA DE ATENCION',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'EN SESION',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'FINALIZADO',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'CANCELADO',NULL);
INSERT INTO FISIKS.ESTADO (ESTID, ESTDESCRIPCION, ESTCOLOR) VALUES (0 ,'ANULADO',NULL);



