CREATE TABLE TURNERO
(
  turId           INTEGER NOT NULL,
  turTitulo       VARCHAR2(45) NULL,
  turDescripcion  VARCHAR2(255) NULL,
  turFechaIni     DATE NULL,
  turFechaFin     DATE NULL,
  turTodoDia      CHAR(1) NULL,
  tur_paeId       INTEGER NULL,
  tur_proId       INTEGER NULL,
  PRIMARY KEY (turId)
);

CREATE SEQUENCE turId
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER trg_turId BEFORE INSERT ON TURNERO  FOR EACH ROW
BEGIN   SELECT turId.NEXTVAL INTO :NEW.turId FROM DUAL; END;
/