CREATE TABLESPACE FISIKS_TBL DATAFILE 
  'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\FISIKS_01.DBF' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

DROP USER FISIKS CASCADE;


CREATE USER FISIKS
  IDENTIFIED BY fisiks
  DEFAULT TABLESPACE FISIKS_TBL
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for FISIKS 
  GRANT CONNECT TO FISIKS;
  GRANT DBA TO FISIKS;
  ALTER USER FISIKS DEFAULT ROLE NONE;
  -- 14 System Privileges for FISIKS 
  GRANT CREATE VIEW TO FISIKS;
  GRANT CREATE TABLE TO FISIKS;
  GRANT CREATE TYPE TO FISIKS;
  GRANT CREATE DATABASE LINK TO FISIKS;
  GRANT DEBUG CONNECT SESSION TO FISIKS;
  GRANT CREATE MATERIALIZED VIEW TO FISIKS;
  GRANT CREATE SYNONYM TO FISIKS;
  GRANT CREATE SEQUENCE TO FISIKS;
  GRANT UNLIMITED TABLESPACE TO FISIKS;
  GRANT CREATE PROCEDURE TO FISIKS;
  GRANT CREATE SESSION TO FISIKS;
  GRANT CREATE JOB TO FISIKS;
  GRANT DEBUG ANY PROCEDURE TO FISIKS;
  GRANT CREATE TRIGGER TO FISIKS;
  -- 1 Tablespace Quota for FISIKS 
  ALTER USER FISIKS QUOTA UNLIMITED ON FISIKS_TBL;
