CREATE OR REPLACE PROCEDURE FISIKS.PRC_PACIENTEOCUPACIONES_INSERT (
    iOPA_PAEID            IN PACIENTEOCUPACIONES.OPA_PAEID%TYPE :=NULL,
    iOPA_OCUID           IN PACIENTEOCUPACIONES.OPA_OCUID%TYPE := NULL)
AS
BEGIN

        INSERT INTO PACIENTEOCUPACIONES
            (OPA_PAEID,
            OPA_OCUID)
        VALUES
            (iOPA_PAEID,
            iOPA_OCUID);

END;
/
