SET DEFINE OFF;
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (13, 'ASSURANCE MEDICALE SA', 'ASSUR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (14, 'CIPREN - PRENSA', 'CIPREN- PRENSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (15, 'INARCO SA - GRAL. PICO-LA PAMPA', 'INARC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (16, 'INSSJYP - RED PRESTACIONAL DEL INTERIOR', 'INSSJ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (17, 'I.P.A.M ', 'I.P.A.M');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (18, 'GER SA ', 'GER S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (19, 'PROFE ENTRE RIOS', 'PROFE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (20, 'PROGRAMA FEDERAL CORDOBA', 'PROFE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (21, 'OBRA SOCIAL DEL PERSONAL DE ESCRIBANOS', 'OSPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (22, 'OBRA SOCIAL DE PETROLEROS', 'OSPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (23, 'OBRA SOCIAL DE LA ACTIVIDAD MINERA', 'OSAM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (24, 'OBRA SOCIAL DE DOCENTES PARTICULARES', 'OSDOP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (25, 'OBRA SOCIAL FERROVIARIA', 'OSFE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (26, 'USAR 50 - OSPECON NO USAR -', 'O.S.P.E.C.O.N.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (27, 'OBRA SOCIAL PARA LA ACTIVIDAD DOCENTE', 'OSPLAD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (28, 'SPM - SISTEMA PROTECCION MEDICA SA', 'SPM -');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (29, 'ASOCIACION MUTUAL DAN', 'ASOCI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (30, 'ASEGURADORES DE CREDITOS DEL MERCOSUR S.A.', 'ASEGU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (31, 'ASEGURADORA FEDERAL ARGENTINA S.A.', 'ASEGU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (32, 'ASEGURADORA DE CAUSIONES', 'ASEGU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (33, 'ASESORES ESPECIALIZADOS SA', 'ASESO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (34, 'ASOC. MUT. FED. CORD. DE FUTBOL', 'ASOC.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (35, 'ASOC. MUT. EMP. POLISEG. CBA', 'ASOC.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (36, 'ASOC. FRANCESA FILANTROPICA Y BENEFICENCIA', 'ASOC.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (37, 'ASSEPDECSPIyC', 'ASSEP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (38, 'ASTF - RIO CUARTO', 'ASTF ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (39, 'ATSA (no usar)', 'ATSA ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (40, 'AUSTRAL MEDICA SA', 'AUSTR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (41, 'AUTODROMOS ARGENTINOS', 'AUTOD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (42, 'BIO RED SA', 'BIO R');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (43, 'BIOLOGIC SALUD', 'BIOLO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (44, 'BRHINES SUDAMERICANA SA - OSPLAD', 'BRHIN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (45, 'CEFRAN', 'CEFRA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (46, 'CENTRO MEDICO SANTA FE', 'CENTR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (47, 'CEPEII - MENDOZA', 'CEPEI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (48, 'CERHA SRT.', 'CERHA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (49, 'CHORNOBROFF GASTON', 'CHORN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (50, 'CIADEA', 'CIADE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (51, 'CIMA SALUD', 'CIMA ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (52, 'CIRCULO MEDICO - VILLA MARIA', 'CIRCU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (53, 'CIRMED - VILLA MERCEDES', 'CIRME');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (54, 'CAJA DE AHORRO Y SEGUROS SA', 'CAJA ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (55, 'CAMARA PREST.SUDESTE', 'CAMAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (56, 'CAMES - SALUD', 'CAMES');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (57, 'COFESA', 'COFES');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (58, 'COMPLEJO SANITARIO - SAN LUIS', 'COMPL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (59, 'COMPLEMED SA', 'COMPL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (60, 'COMPLEJIDAD MEDICA', 'COMPL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (61, 'CONSTRUIR', 'CONST');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (62, 'CONVENIO TRANSFUSIONAL - VILLA MARIA', 'CONVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (63, 'CONVENIO TRANSF. SER - SA - MUC', 'CONVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (64, 'CONVENIO TRANSF.- MARCOS JUAREZ', 'CONVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (65, 'CONVENIO TRANSF.- CORRAL DE BUSTOS', 'CONVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (66, 'COOP.DE TRABAJO ALIANZA LTDA', 'COOP.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (67, 'COOPERATIVA MEDICA RIO CUARTO', 'COOPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (68, 'COOPERATIVA MEDICA - V.MARIA', 'COOPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (69, 'COOPERATIVA FEL LTDA', 'COOPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (70, 'COOPERATIVA AGRICOLA LTDA.', 'COOPE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (71, 'CORDOBA SALUD SA', 'CORDO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (72, 'COSEME - OSPLAD', 'COSEM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (73, 'CPTC - HOSP. PRIVADO', 'CPTC ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (74, 'CONCIENCIA SRL', 'CONCI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (75, 'FEDERACION MEDICA', 'FEM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (76, 'CUCAIBA', 'CUCAI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (77, 'CUDAIO', 'CUDAI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (78, 'CUYO PRESTADORA DE SALUD SA', 'CUYO ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (79, 'D Y C - MANAGEMENT MEDICAL SA', 'D Y C');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (80, 'DAMSU', 'DAMSU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (81, 'DIMSA SA', 'DIMSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (82, 'DINAMIC SISTEM - ONCATIVO', 'DINAM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (83, 'DIR. DERIVACION - LA RIOJA', 'DIR. ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (84, 'DOSUBA', 'DOSUB');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (85, 'EPI SA', 'EPI S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (86, 'FARMA', 'FARMA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (87, 'FATA S.A.', 'FATA ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (88, 'FAUPPA - CAP.FED.', 'FAUPP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (89, 'FEDERACION PATRONAL SEGUROS DE RETIRO S.A.', 'FEDER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (90, 'MUTUAL FEDERADA SALUD 25 DE JUNIO SPR', 'FEDER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (91, 'FEDERACION ODONTOLOGICA', 'FEDER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (92, 'FEMECOSS', 'FEMEC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (93, 'FEMEDICA', 'FEMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (94, 'FEMOS', 'FEMOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (95, 'FONDO NAC.REC.URUGUAY', 'FONDO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (96, 'FORO DE LA SEG.SOCIAL ARGENTINA-OSPEVIC', 'FORO ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (97, 'FRESENIUS MEDICAL CARE', 'FRESE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (98, 'FUNDEMUR', 'FUNDE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (99, 'G y S SA', 'G y S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (100, 'GEMSER SA', 'GEMSE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (101, 'DASUTEN - FUSAVIN', 'DASUT');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (102, 'DAVERLEY SA', 'DAVER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (103, 'DERIMED', 'DERIM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (104, 'GERENCIAR SALUD - CERAMISTAS', 'GEREN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (105, 'GERENCIA MEDICA ASISTENCIAL', 'GEREN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (106, 'GRAL. SERV. SOCIALES', 'GRAL.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (107, 'HIM ART', 'HIM A');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (108, 'HOSP. ITALIANO PLAN SALUD', 'HOSP.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (109, 'HOSP. FRANCISCO LOPEZ LIMA - RIO NEGRO', 'HOSP.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (110, 'HOSPITAL SAN MARTIN  - ENTRE RIOS', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (111, 'HOSPITAL PROVINCIAL - SAN LUIS', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (112, 'HOSPITAL DR. HUMBERTO NOTTI', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (113, 'HOSPITAL DR. ENRIQUE VERA BARROS - LA RIOJA', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (114, 'HOSPITAL RAWSON - SAN JUAN', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (115, 'HOSPITAL PROVINCIAL NEUQUEN', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (116, 'HOSPITAL PRESIDENTE PLAZA - LA RIOJA', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (117, 'HOSPITAL PEDRO MOVILIASKY', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (118, 'HOSPITAL ORLANDO ALASSIA - STA.FE', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (119, 'HOSPITAL NACIONAL CLINICAS', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (120, 'HOSPITAL ESPAÑOL', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (121, 'HOSPITAL DR. ALASSIA - SANTA FE', 'HOSPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (122, 'I.P.S.MISIONES', 'I.P.S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (123, 'IMG LATIN AMERICA', 'IMG L');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (124, 'IMOS', 'IMOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (125, 'IMPLANTES RB SRL', 'IMPLA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (126, 'INCAIMEN', 'INCAI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (127, 'INST.DE SEGURO DEL CHACO', 'INST.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (128, 'INST. SERV. SOC. TIERRA DEL FUEGO', 'INST.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (129, 'INTERACCION ART', 'INTER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (130, 'INTERACCION SEGUROS S.A.', 'INTER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (131, 'INTERMUT - MUTUAL LA CENTRAL', 'INTER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (132, 'INTERMEDICA', 'INTER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (133, 'INTERMED SA', 'INTER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (134, 'IAPOS - SANTA FE', 'IAPOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (135, 'JOCKEY CLUB RIO CUARTO', 'JOCKE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (136, 'LA CENTRAL - CENTRO MUT. PROF. MEDICOS', 'LA CE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (137, 'LA FLORESTA', 'LA FL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (138, 'LAB.HEMODERIVADOS UNC', 'LAB.H');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (139, 'LABORATORIOS BIOMEDICOS', 'LABOR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (140, 'MAXIMED', 'MAXIM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (141, 'MEC - RIO CUARTO', 'MEC -');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (142, 'MUTUAL FEDERADA 25 DE JUNIO (NO USAR)', 'MUTUA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (143, 'OSDE BINARIO - LABOULAYE', 'OSDE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (144, 'OSPSIP', 'OSPSI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (145, 'PREME MEDICINA PRIVADA - CORDOBA.', 'PREME');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (146, 'NO USAT - USAR 3158 - PROTECCION', 'PROTE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (147, 'PROYECCION SEGUROS DE RETIRO S.A.', 'PROYE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (148, 'SECRETARIA DE SALUD - PARANA', 'SECRE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (149, 'SEG. INCA', 'kmhty');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (150, 'SERVE SALUD', 'SERVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (151, 'SERVICIO OCUPACIONAL DE SALUD', 'SERVI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (152, 'SET SA', 'SET S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (153, 'TRANSPORTE MARVEL LIMITADA', 'TRANS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (154, 'TRANSPORTADORA D M  S.A.', 'TRANS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (155, 'TRANSAX - VOLKWAGEN ARGENTINA', 'TRANS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (156, 'SIMSA SA', 'SIMSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (157, 'SIPASS', 'SIPAS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (158, 'SIS CAT', 'SIS C');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (159, 'SISTEMA OPCIONAL DE SALUD', 'SISTE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (160, 'SUOEM', 'SUOEM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (161, 'UNION MEDICA', 'UNION');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (162, 'URGARA', 'URGAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (163, 'UTE SALUD - SAN LUIS', 'UTE S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (164, 'VIAL 3 SA', 'VIAL ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (165, 'WELL BEING - UOM', 'WELL ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (166, 'YPF GAS SA', 'YPF G');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (167, 'CORBIET SA', 'CORBI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (168, 'VISITAR SRL', 'VISITAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (169, 'SOLIDARIA SALUD', 'SS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (170, 'IPAM - RED VIOLETA - COPRIN UTE', 'COPRIN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (171, 'MAXIMED INTERIOR', 'MAXIMED INTERIOR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (172, 'THALLION PHARMACEUTICALS INC.', 'TP INC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (173, 'INSTITUTO DE SEGURIDAD DEL TRABAJO', 'IST');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (174, 'INTER MUTUELLES ASSISTANCE G.I.E.', 'IMA GIE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (175, 'MUTUAIDE ASSISTANCE', 'MUTUAIDE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (176, 'OBRA SOCIAL DEL PERSONAL AERONAUTICO', 'OSPA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (177, 'CENTRO GALLEGO DE BUENOS AIRES', '.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (178, 'MEDICOS ASOCIADOS SRL CLINICA PRIVADA', 'MACP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (179, 'PREMEDICAL', 'PREMEDICA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (180, 'ADOS - SAN JUAN', 'ADOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (181, 'PROGRAMA INCLUIR SALUD', 'PROG IS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (182, 'ASOCIACION DE OBRAS SOCIALES DE ROSARIO', 'AOSR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (183, 'SIMARA S.A.', 'SIMARA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (184, 'EUROP ASSISTANCE S.A.', 'UNIVE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (185, 'OBRA SOCIAL DE DIRECCION - WITCEL S.A.', 'WITCEL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (186, 'SMG COMPAÑIA ARGENTINA DE SEGUROS S.A.', 'SMG C');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (187, 'TRADICION SEGUROS S.A.', 'TRADI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (188, 'ANTARTIDA COMPAÑIA ARGENTINA DE SEGUROS S.A.', 'ANTAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (189, 'NATIVA COMPAÑIA ARGENTINA DE SEGUROS S.A.', 'NATIV');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (190, 'LA NUEVA COOPERATIVA DE SEGUROS LIMITADA', 'LA NU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (191, 'BRADESCO ARGENTINA DE SEGUROS S.A.', 'BRADE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (192, 'TRAINMET SEGUROS SOCIEDAD ANONIMA', 'TRAIN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (193, 'LUZ ASEGURADORA DE RIESGOS DEL TRABAJO S.A.', 'LUZ A');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (194, 'QBE ARGENTINA ART SA', 'QBE A');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (195, 'PROFUTURO CIA. DE SEGUROS DE RETIRO S.A.', 'PROFU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (196, 'PROFUTURO CIA. DE SEGUROS DE VIDA S.A.', 'PROFU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (197, 'METROPOLITAN LIFE SEGUROS DE RETIRO S.A.', 'METRO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (198, 'CONSORCIO DE PRESTADORES DE SALUD', 'CONSO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (199, 'PREVENCION MEDICA INTEGRAL S.A.', 'CONSO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (200, 'TESTIMONIO COMPAÑIA DE SEGUROS DE VIDA S.A.', 'TESTI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (201, 'CHUBB ARGENTINA DE SEGUROS S.A.', 'CHUBB');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (202, 'GALICIA RETIRO COMPAÑIA DE SEGUROS S.A.', 'GALIC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (203, 'GALICIA VIDA COMPAÑIA DE SEGUROS S.A.', 'GALIC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (204, 'NACION SEGUROS S.A.', 'NACION');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (205, 'BINARIA SEGUROS DE VIDA S.A.', 'BINAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (206, 'PREVINCA SEGUROS SOCIEDAD ANONIMA', 'PREVI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (207, 'PREVISOL COMPAÑIA DE SEGUROS DE VIDA S.A.', 'PREVI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (208, 'CERTEZA COMPAÑIA DE SEGUROS S.A.', 'CERTE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (209, 'FDF SEGUROS DE PERSONAS S.A.', 'FDF S');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (210, 'PROVINCIA SEGUROS SOCIEDAD ANONIMA', 'P.S.S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (211, 'SAN PATRICIO SEGUROS DE VIDA Y SALUD S.A.', 'SAN P');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (212, 'HSBC-LA BUENOS AIRES SEGUROS S.A.', 'HSBC-');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (213, 'ORIGENES SEGUROS DE RETIRO S.A.', 'ORIGE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (214, 'SENTIR SEGUROS SOCIEDAD ANONIMA', 'SENTI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (215, 'ART LIDERAR ASEGURADORA DE RIESGO DE TRABAJO', 'LIDERAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (216, 'ORBIS COMPAÑÍA ARGENTINA DE SEGUROS S.A.', 'ORBIS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (217, 'JUNCAL COMPAÑÍA DE SEGUROS DE VIDA S.A.', 'JUNCA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (218, 'HOSPITAL ALEMAN', 'HOSPITAL ALEMAN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (219, 'OBRA SOCIAL DE LOCUTORES', 'OSDEL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (220, 'O.S. DEL PERSONAL DE SOC.DE AUTORES Y AFINES', 'OSPESA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (221, 'OBRA SOCIAL DEL PERSONAL DE JABONEROS', 'OSPEJ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (222, 'NOBLE S. A. ASEGURADORA DE RESP. PROFESIONAL', 'NOBLE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (223, 'ESCUDO SEGUROS S.A.', 'ESCUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (224, 'RIO COMPAÑIA DE SEGUROS S.A.', 'RIO C');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (225, 'PRUDENTIAL SEGUROS S.A.', 'PRUDE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (226, 'B.H.N. SEGUROS GENERALES S.A.', 'B.H.N');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (227, 'VIRGINIA SURETY COMPAÑIA DE SEGUROS S.A.', 'VIRGI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (228, 'CARDIF SEGUROS S.A.', 'CARDI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (229, 'LIBERTY SEGUROS ARGENTINA S.A.', 'L.S.A. S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (230, 'COSENA SEGUROS S.A.', 'COSEN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (231, 'SWISS MEDICAL ART', 'SMG');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (232, 'ASOCIACION CIVIL AFS PROGRAMA DE INTERCAMBIO', 'ACAPI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (233, 'BRISTOL MEDICINE S.R.L.', 'BRISTOL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (234, 'CENTRO DE IMAGENES DEL SUQUIA S.A.', 'CSUQ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (235, 'OBRA SOCIAL DE TECNICOS DE FUTBOL', 'OSTECF');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (236, 'OBRA SOCIAL DE RECIBIDORES DE GRANOS Y ANEXOS', 'OSRGA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (237, 'TECNOLOGIA EN SERVICIOS URBANOS - TESUR S.A.', 'TESUR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (238, 'OBRA SOCIAL DEL PERSONAL LADRILLERO', 'OSPL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (239, 'MAPFRE ARGENTINA', 'M.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (240, 'OBRA SOCIAL DEL PERSONAL DE TELEVISION', 'OSPETV');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (241, 'CNA ART', 'CNA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (242, 'OBRA SOCIAL DEL PODER JUDICIAL DE LA NACION', 'P.JUDICIAL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (243, 'O. S. DE LAS ASOC. DE EMPLEADOS DE FARMACIA', 'OSADEF');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (244, 'OBRA SOCIAL DE LA CIUDAD DE BUENOS AIRES', 'OSCBA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (245, 'OBRA SOCIAL BANCARIA ARGENTINA', 'OSBA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (246, 'OBRA SOCIAL DE CERAMISTAS', 'OSCE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (247, 'SOCIEDAD ITALIANA DE MORON (PLAN B)', 'S.I.M. B""');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (248, 'OBRA SOCIAL DE CHOFERES DE CAMIONES', 'OSChoCa');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (249, 'OBRA SOCIAL DEL PERSONAL DE LA CONSTRUCCION', 'OSPECON');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (250, 'OBRA SOCIAL DE CONDUCTORES NAVALES', 'OSCN(CF)');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (251, 'OBRA SOCIAL DEL PERSONAL GRAFICO', 'OSPG');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (252, 'OBRA SOCIAL DEL PERSONAL DE MAESTRANZA', 'OSPMae');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (253, 'OBRA SOCIAL DEL PERSONAL MARITIMO', 'OSPMar');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (254, 'OBRA SOCIAL DEL PERSONAL MOSAISTA', 'OSPMos');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (255, 'OBRA SOCIAL DE COMISARIOS NAVALES', 'OSCN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (256, 'OBRA SOCIAL DEL PERSONAL DE PANADERIAS', 'OSPPan');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (257, 'OBRA SOCIAL DEL PETROLEO Y GAS PRIVADO', 'OSPEGAP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (258, 'OBRA SOCIAL DEL PERSONAL DE LA PUBLICIDAD', 'OSPP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (259, 'OBRA SOCIAL DE SERENOS DE BUQUES', 'OSSBuq.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (260, 'OBRA SOCIAL DE EMPLEADOS TEXTILES Y AFINES', 'OSETyA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (261, 'OBRA SOCIAL DEL PERSONAL DE LA ACTIVIDAD VIAL', 'OSPAV');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (262, 'OBRA SOCIAL ACCION SOCIAL DE EMPRESARIOS', 'ASE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (263, 'HOSPITAL BRITANICO DE BUENOS AIRES', 'HB');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (264, 'EL COMERCIO COMPAÑIA DE SEGUROS', 'EL COMERCIO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (265, 'ACA SEGUROS', 'ACA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (266, 'AUTOMOVIL CLUB ARGENTINO -ACA-', 'ACA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (267, 'GALENO ART S.A.', 'GALENO ART');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (268, 'OBRA SOCIAL DE DIRECCION OSDO', 'O.S.DIRECC.OSDO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (269, 'OBRA SOCIAL DE VOLKSWAGEN ARGENTINA S.A.', 'OBRA ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (270, 'TRIUNFO COOPERATIVA DE SEGUROS LIMITADA', 'TRIUN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (271, 'TRES PROVINCIAS SEGUROS DE PERSONAS S.A.', 'TRES ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (272, 'ITER  MEDICINA CBA', 'ITER ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (273, 'HANDELS SA - AMPARA SALUD', 'AMPARA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (274, 'HOSP. PRIVADO  - CONV. VW', 'HOSP.P.CBA.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (275, 'OSDE BINARIO', 'osde');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (276, 'OMINT', 'O.M.I.N.T.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (277, 'BOSTON SEGUROS', 'BOSTON');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (278, 'MET - Medicina Privada', 'MET CARD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (279, 'OBRA SOCIAL DE EMPLEADOS DE PRENSA DE CORDOBA', 'OSEPC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (280, 'OBRA SOCIAL CONDUCTORES DE TAXIS DE CORDOBA', 'OSCT');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (281, 'OBRA SOCIAL DE PETROLEROS DE CORDOBA', 'OSPECOR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (282, 'GEA SA', 'GEA SA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (283, 'MEDIFE', 'MEDIFE ASOC. CIVIL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (284, 'ASISTIR SALUD SERVICIOS MEDICOS', 'ASISTIR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (285, 'HOSPITAL PRIVADO CENTRO MEDICO DE CBA S.A.', 'HP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (286, 'FEDERACION BIOQUIMICOS PCIA DE CBA', 'FED.BIOQ.P.CBA.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (287, 'OBRA SOCIAL EMPLEADOS PUBLICOS CATAMARCA', 'OSEP CATAMARCA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (288, 'FAMILY SALUD', 'FAMILY S.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (289, 'SE.ME.GER. S.R.L.', 'SEMEGER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (290, 'ASOCIACION DE CLINICAS Y SANATORIOS', 'ACYSO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (291, 'ADMINISTRACION PROVINCIAL DEL SEGURO DE SALUD', 'APROSS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (292, 'IPAM', 'IPAM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (293, 'SERVIRED', 'SERVIRED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (294, 'SWISS MEDICAL S.A.', 'SWISS MEDICAL S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (295, 'ACA SALUD', 'ACA SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (296, 'PARQUE SALUD S.A.', 'PARQUE SALUD S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (297, 'POLICIA FEDERAL SUPERINTENDENCIA DE BIENESTAR', 'POLICIA FEDERAL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (298, 'PROTECCION MEDICA SRL', 'PROTECCION MEDICA SR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (299, 'CRS - PRESTADORES DE SALUD', 'CRS-PRES. SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (300, 'ACCION SOCIAL PERSONAL UNIVERSIDAD RIO CUARTO', 'ASPURC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (301, 'ASOCIACION ESPAÑOLA SOCORROS MUTUOS', 'ASOCIACION ESPAÑOLA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (302, 'REYLES S.A.', 'ARISTON');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (303, 'MUTUAL INTERCOOPERATIVA PARA  LA SALUD', 'A.M.I.CO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (304, 'GALENO ARGENTINA S.A.', 'GALENO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (305, 'CLINICA PRIVADA CAMILO ALDAO S.R.L.', 'C.P.C.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (306, 'PREMED S.A.', 'PREMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (307, 'SEGURO DE BIENES Y RESGUARDO DEL AUTOMOTOR', 'SBRA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (308, 'SINDICATO DE OBREROS Y EMPLEADOS MUNICIPALES', 'SEOM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (309, 'S.A. ASISTIR EN SALUD', 'AS EN SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (310, 'CGS.SA ZURICH HEALTH', 'ZH');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (311, 'EXPRESO DIFERENCIAL  CBA - RIO IV - BUS LEP -', 'LEP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (312, 'ASOCIACION POETA LUGONES MUTUAL C Y D', 'LUGONES');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (313, 'SISTEMA INTEGRADO DE PRESTADORES DE SALUD SA', 'SIPSSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (314, 'SANARTE', 'SANARTE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (315, 'UNION KRANKENVERSICHERUNG', 'UNION KRANKENVERSICH');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (316, 'DONACIONES', 'DNCNS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (317, 'CONVENIO TRANSFUSIONAL LA CARLOTA', 'CONVENIO TRANSFUSION');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (318, 'CONVENIO TRANSFUSIONAL', 'CONVENIO TRANSFUSION');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (319, 'PRIVERAL S.A.', 'PRIVERAL S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (320, 'CENTRO DE ATENCIÓN MEDICA', 'CENTRO DE ATENCIÓN M');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (321, 'UNIMED SA', 'UNIMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (322, 'PLANAMED S.A.', 'PLANAMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (323, 'HORIZONTE  ART', 'HORIZONTE ART');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (324, 'C.M.S. S.A.', 'CMS SA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (325, 'RED PRESTACIONAL CBA SRL', 'RED PREST');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (326, 'GILSA S.R.L.', 'GILSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (327, 'ALIANZ ARGENTINA', 'ALIANZ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (328, 'COSEME S.A.', 'COSEME  S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (329, 'AGRUPACION DE COLABORACION GRUPO PARAMEDIC', 'PARAMEDIC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (330, 'SANATORIO CORRIENTES S.R.L.', 'S.C.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (331, 'SAN CRISTOBAL SEGUROS GENERALES - CORDOBA', 'S.C.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (332, 'MESBLA S.A.', 'MESBLA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (333, 'ASEGURADORA FEDERAL ARGENTINA S.A. - CORDOBA', 'F.A.C.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (334, '24 hs S.A.', '24 hs S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (335, 'COOPERATIVA DE TRABAJO MERCOCENTRO', 'CTM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (336, 'ASESORES DE CORDOBA S.A. - ASECOR', 'ASECOR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (337, 'RED HUMANA', 'REDH');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (338, 'DOCTHOS. Sa.', 'DOCTHOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (339, 'EL COMERCIO SEGUROS - CORDOBA', 'EL COMERCIO CBA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (340, 'INSTITUTO MEDICO DEAN FUNES S.A. - Convenio', 'DF');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (341, 'CONVENIO INSTITUTO MEDICO STRUSBERG SA', 'CIMS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (342, 'SEGUROS PARANA', 'SP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (343, 'SEGUROS LA CAJA S.A.', 'LA CA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (344, 'FEMESA RED ARGENTINA DE SALUD', 'FEMESA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (345, 'DENTIS ODONTOLOGIA PRIVADA', 'DENTIS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (346, 'INTERMEDICINA', 'INTERMEDICINA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (347, 'INSTITUTO PRIVADO DE RADIOTERAPIA', 'INSTITUTO PRIVADO DE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (348, 'Cesopol Salud Oncativo', 'Cesopol Salud Oncati');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (349, 'ASOCIACION MUTUAL HERCULES', 'HERCULES');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (350, 'CEMIC', 'CEMIC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (351, 'ASOCIACION MUTUAL RURALISTA', 'AMUR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (352, 'COOP. DE TRABAJO DE VILLA DOLORES', 'COOP. DE TRABAJO DE ');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (353, 'UNION FEDERAL SUNCHALES', 'UNION FEDERAL SUNCHA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (354, 'HOSPITAL INFANTIL MUNICIPAL', 'HOSPITAL INFANTIL MU');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (355, 'SOCORRO MEDICO PRIVADO CORDOBA S.A.', 'VITAL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (356, 'PROFE LA RIOJA', 'PROFE LA RIOJA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (357, 'PROFE - CALETA OLIVIA - SANTA CRUZ', 'PROFE C.O.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (358, 'GOBIERNO DE TIERRA DEL FUEGO', 'GOB');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (359, 'PROFE Tierra del Fuego', 'PROFE T.F.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (360, 'AUSTRAL OMI', 'OMI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (361, 'O. S. DEL PERSONAL DE LA ACTIVIDAD FRUTICOLA', 'OSPAF');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (362, 'MINISTERIO DE SALUD PUBLICA DE CORRIENTES', 'MSCORR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (363, 'IOSCOR - CORRIENTES', 'IOSCOR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (364, 'INSTITUTO DE SEGUROS DE JUJUY', 'INST.DE SEG.DE JUJUY');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (365, 'BOREAL', 'boreal');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (366, 'EL PROGRESO + ASTRO COMPAÑIA DE SEGUROS S.A.', 'EL PR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (367, 'SERVICIO MEDICO PREVISIONAL', 'S.M.P.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (368, 'HOSPITAL DR. LUCIO MOLAS - LA PAMPA', 'HOSP.LA PAMPA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (369, 'ASOCIACION MUTUAL DEL PARANA', 'ASMP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (370, 'SANCOR COOPERATIVA DE SEGUROS LIMITADA', 'SANCO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (371, 'UNIDOS SEGUROS DE RETIRO SOCIEDAD ANONIMA', 'UNIDO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (372, 'NUEVA MUTUAL DE SERVICIOS', 'NUMUSE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (373, 'PROFE SALTA', 'PROFESAL');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (374, 'LA VELOZ SEGUROS S.A.', 'LA VE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (375, 'SUMICLI ASOCIACION MUTUAL DE SEGUROS', 'SUMIC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (376, 'LA PREVISORA S.A. SEGUROS DE SEPELIO', 'LA PR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (377, 'PROFE SAN JUAN', 'PROFE SAN JUAN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (378, 'DIRECCION DE OBRA SOCIAL GOBIERNO DE SAN JUAN', 'GOBSJUAN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (379, 'MINISTERIO DE SALUD DE SAN JUAN', 'S.J.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (380, 'OBRA SOCIAL PETROLEROS PRIVADOS', 'OS.PE.PRI.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (381, 'ISSN-NEUQUEN', 'ISSN-');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (382, 'SUME SALUD', 'SUME');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (383, 'ASOCIACION MUTUAL MEDICA DE VILLA MARIA', 'AMM-VILLA MARIA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (384, 'PROFE CATAMARCA', 'PROFE CAT');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (385, 'HOSPITAL INTERZONAL DE NIÑOS EVA PERON', 'HOSP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (386, 'RED HUMANA - DEAN FUNES', 'RED HUMANA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (387, 'PROGRAMA FEDERAL SANTIAGO DEL ESTERO', 'PROFE SGO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (388, 'I.A.C.A. LABORATORIOS', 'IACA LABORATORIOS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (389, 'CAR MED SRL', 'CAR MED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (390, 'CLUB ATLETICO Y BIBLIOTECA CENTRAL ARGENTINO', 'CLUB');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (391, 'DIRECCION OBRA SOCIAL DEL ESTADO PROVINCIAL', 'DOSEP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (392, 'CENTRO ONCOLOGICO - DOSEP', 'CO - DOSEP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (393, 'PROFE SAN LUIS', 'PROFE S.L.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (394, 'SERVICIO DE HEMOTRAPIA DR. CREADO NELIO', 'SERVICIO DE HEMOTERA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (395, 'HOSPITAL MUNICIPAL EVA PERON.', 'HMEP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (396, 'SANATORIO DE LA TRINIDAD PRIVADO SRL', 'SANATORIO DE LA TRIN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (397, 'PROFE SANTA FE', 'PROFE S.F.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (398, 'ASOCIACION DE OBRAS SOCIALES DE TRELEW', 'ASOC.DE O.S. TRELEW');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (399, 'INSTITUTO DE OBRA SOCIAL DE ENTRE RIOS', 'IOSER');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (400, 'ITERMEDICINA SA - ENTRE RIOS', 'ITERM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (401, 'SAN CRISTOBAL SEGUROS GENERALES', 'S.G.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (402, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE ROSARIO', 'OSPPRos.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (403, 'LA SEGUNDA ART', 'LA SE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (404, 'LA SEGUNDA CIA. DE SEGUROS DE PERSONAS S.A.', 'LA SEGUNDA C.S.P.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (405, 'DELTA SALUD S. A.', 'DELTA SALUD S. A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (406, 'PREVINCA SALUD', 'PREV. SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (407, 'ITAL MEDIC', 'IM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (408, 'EMPRESA PROVINCIAL DE ENERGIA DE SANTA FE', 'EPESF');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (409, 'CONTENCION MEDICA', 'CONMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (410, 'SANATORIO PLAZA, PLAN DE SALUD', 'SANATORIO PLAZA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (411, 'OBRA SOCIAL DEL PERSONAL DE PRENSA DE TUCUMAN', 'OSPRENTUC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (412, 'PROFE TUCUMÁN', 'PROFE TUC.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (413, 'COBERTURA DE SALUD S.A.', 'COBSALSA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (414, 'GRUPO PROYECTOR SRL - SR MEDICINA ASISTENCIAL', 'SRMAGP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (415, 'MUTUAL MEDICA RIO CUARTO', 'MMRC');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (416, 'INSTITUTO MUNICIPAL DE PREVISION SOCIAL.', 'MUNICIPALES');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (417, 'ENTE DESCENTRALIZADO DE CONTROL MUNICIPAL', 'EDECOM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (418, 'SUMA SALUD S.A.', 'SUMA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (419, 'POLICLINICO PRIVADO SAN LUCAS U.T.E.', 'Policlinico Privado');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (420, 'RIO URUGUAY COOPERATIVA DE SEGUROS', 'RIO URUG.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (421, 'SEGURO METAL', 'SECITTA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (422, 'CEM SRL', 'CEM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (423, 'CLINICA PRIVADA SRL (VILLA DOLORES)', 'C.P.S.R.L');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (424, 'SALUD Y SERVICIOS SRL', 'SYS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (425, 'COCHERIA ITATI SERVICIOS SOCIALES S.R.L.', 'ITATI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (426, 'CAMI SALUD', 'CAMI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (427, 'TAJAMAR SALUD S.R.L.', 'TS');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (428, 'NOBIS S.A. - MEDICINA PRIVADA', 'NOBIS -MEDIC. PRIVAD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (429, 'VIDA PLENA (OLIVA)', 'VIDA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (430, 'LO-MAR S.A. Division Salud', 'LO-MAR');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (431, 'MAPFRE ART', 'MAPFRE ART');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (432, 'COBERTURA DE SALUD - JUSTINIANO POSSE', 'C.SALUD JP');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (433, 'COBERTURA DE SALUD -  BELL VILLE', 'C.SALUD B.V.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (434, 'SANATORIO INDEPENDENCIA S.R.L.', 'S.I.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (435, 'ASOCIACION ECLESIASTICA DE SAN PEDRO', 'SAN PEDRO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (436, 'ASOCIACION ARG. MUTUAL DEL MOTOCICLISTA', 'AMM');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (437, 'FUNDACION CO.ME.I.', 'PLAN DE SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (438, 'COPAN COOPERATIVA DE SEGUROS LIMITADA', 'COPAN');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (439, 'FEDERACION PATRONAL SEGUROS S.A.', 'F.P.SEG.S.A.');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (440, 'INSTITUTO DE OBRA MEDICO ASISTENCIAL', 'IOMA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (441, 'GENZYME DE ARGENTINA S.A.', 'GENZY');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (442, 'LA PERSEVERANCIA SEGUROS SOCIEDAD ANONIMA', 'LA PE');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (443, 'ASISTENCIA SANITARIA INTEGRAL', 'ASI');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (444, 'MAYOR SALUD', 'MAYOR SALUD');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (445, 'BUENOS AIRES SERVICIOS DE SALUD - BASA S.A.', 'BASA');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (446, 'MINISTERIO DE SALUD DEL CHUBUT', 'MSCh');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (447, 'LABORATORIO PRA-PROTOCOLO', 'PRA-PROTOCOLO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (448, 'AXA-ASSISTANCE ARGENTINA SA', 'AXA-ASSISTANCE ARG');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (449, 'OBRA SOCIAL DE DIRECCION', 'OSDO');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (450, 'LABOUMED S.R.L.', 'LABOUMED');
Insert into FISIKS.OBRASOCIAL
   (OSOID, OSODESCRIPCION, OSOSIGLA)
 Values
   (451, 'OBRA SOCIAL DE VAREADORES', 'OSV');
COMMIT;
