ALTER TABLE FISIKS.MATRICULATIPO
 DROP PRIMARY KEY CASCADE;

DROP TABLE FISIKS.MATRICULATIPO CASCADE CONSTRAINTS;

CREATE TABLE FISIKS.MATRICULATIPO
(
  MTTID           INTEGER                       NOT NULL,
  MTTDESCRIPCION  VARCHAR2(45 BYTE)
)
TABLESPACE FISIKS_TBL
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE SEQUENCE FISIKS.MTTID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER FISIKS.trg_mttid BEFORE INSERT ON FISIKS.MATRICULATIPO  FOR EACH ROW
BEGIN   SELECT mttid.NEXTVAL INTO :new.mttid FROM DUAL; END;
/


ALTER TABLE FISIKS.MATRICULATIPO ADD (
  PRIMARY KEY
 (MTTID)
    USING INDEX 
    TABLESPACE FISIKS_TBL
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));



ALTER TABLE FISIKS.MATRICULA
 ADD (MTR_MTTID  INTEGER);

ALTER TABLE FISIKS.MATRICULA
 ADD FOREIGN KEY (MTR_MTTID) 
 REFERENCES FISIKS.MATRICULATIPO (MTTID);