INSERT INTO FISIKS.MATRICULATIPO (MTTID, MTTDESCRIPCION) VALUES (0,'PROVINCIAL');
INSERT INTO FISIKS.MATRICULATIPO (MTTID, MTTDESCRIPCION) VALUES (0,'NACIONAL');
INSERT INTO FISIKS.MATRICULATIPO (MTTID, MTTDESCRIPCION) VALUES (0,'ESPECIALIDAD');
COMMIT;