ALTER TABLE FISIKS.PACIENTEOS
 ADD (OSPNROSOCIO  INTEGER);

ALTER TABLE FISIKS.OCUPACIONES
RENAME COLUMN OCUSEDENTARIA TO OCU_OPTID;
ALTER TABLE FISIKS.OCUPACIONES
MODIFY(OCU_OPTID INTEGER);


CREATE TABLE OCUPACIONESTIPO (
  optId INT NOT NULL,
  optDescripcion VARCHAR2(45) NULL,
  PRIMARY KEY (optId));

CREATE SEQUENCE optid
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

CREATE OR REPLACE TRIGGER trg_optid BEFORE INSERT ON OCUPACIONESTIPO  FOR EACH ROW
BEGIN   SELECT optid.NEXTVAL INTO :new.optid FROM DUAL; END;
/


ALTER TABLE FISIKS.OCUPACIONES
 ADD CONSTRAINT FK_OCU_OCUPACIONTIPO 
 FOREIGN KEY (OCU_OPTID) 
 REFERENCES FISIKS.OCUPACIONTIPO (OPTID);

ALTER TABLE PACIENTE
ADD PAEPESO DECIMAL(8,2);

ALTER TABLE FISIKS.DOMICILIO
 ADD (DOMDESCRIPCION  VARCHAR2(45));


ALTER TABLE FISIKS.OBRASOCIAL
 ADD (OSOCODIGO  VARCHAR2(45));


ALTER TABLE FISIKS.PERSONA
 ADD (PSNDOMICILIO  VARCHAR2(50))
/


