Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'ESPECIALIDAD COLUMNA VERTEBRAL Y EXTREMIDADES');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA CARDIOVASCULAR');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA ERGONOMIA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA GERIATRICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA GINECOLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA NEUROLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA NEUROLOGICA INFANTIL');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA PEDIATRICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA PLASTICA Y ESTETICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA RESPIRATORIA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA REUMATOLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA SALUD MENTAL Y PSIQUIATRIA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA SALUD OCUPACIONAL Y TRABAJO');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA TORACICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA TRATAMIENTOS ALTERNATIVOS');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'FISIOTERAPIA UROGINECOLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'KINESIOLOGIA DEPORTIVA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'KINESIOLOGIA NEUROLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'KINESIOLOGIA NEUROLOGICA');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'ORTOPEDIA TRAUMATOLOGIA INFANTIL Y ADULTO');
Insert into FISIKS.ESPECIALIDADES
   (EPCID, EPCDESCRIPCION)
 Values (0,'REHABILITACION CARDIORRESPIRATORIA');
COMMIT;


Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'ASUNTOS PERSONALES');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'ENFERMEDAD');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'EXAMEN');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'FALLECIMIENTO');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'MATERNIDAD');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'MATRIMONIO');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'MUDANZA');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'NACIMIENTO');
Insert into FISIKS.LICENCIASTIPO
   (LCTID, LCTDESCRIPCION)
 Values (0,'VACACIONES');
COMMIT;